
/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/Dataset/SegSperm/train
/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/Dataset/SegSperm/test_small
GPU dostÄ™pne: NVIDIA GeForce RTX 3090
Epoch 1, Train Loss: 0.6203319893942939, Validation Loss: 0.40821921825408936, Validation IOU: 0.6540552362513012
Traceback (most recent call last):
  File "/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/Kod/train.py", line 241, in <module>
    main(model, train_loader, val_loader, optimizer,scheduler, loss_fn, config.epochs,aug,t_aug,save_name)
  File "/media/cal314-1/9E044F59044F3415/Marcin/noisy_labels/Kod/train.py", line 153, in main
    torch.save(model.state_dict(), model_path)
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/torch/serialization.py", line 618, in save
    with _open_zipfile_writer(f) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/torch/serialization.py", line 492, in _open_zipfile_writer
    return container(name_or_buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cal314-1/miniconda3/envs/marcin/lib/python3.11/site-packages/torch/serialization.py", line 463, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: File /media/cal314-1/9E044F59044F3415/Marcin/Data/model/Annotator2_Model:smpUNet++_AugmentationTrue_OptimizerAdam_SchedulerCosineAnnealingLR_Epochs_300_Batch_Size6_Start_lr0.0001_LossCrossEntropyLoss_Timestamp2024-01-05-10-21_best_model cannot be opened.